/**
 * The complete IANA "Well-Known URIs" registry (fetched 2026-08-05), encoded
 * as reference entries. Every suffix gets an auto-generated reference page;
 * entries with a `deepDive` slug link to a full explainer.
 */

import type { RegistryEntry } from "./types.ts";

const RFC = (num: number) => `https://www.rfc-editor.org/rfc/rfc${num}`;

export const IANA: RegistryEntry[] = [
  {
    suffix: "acme-challenge",
    uri: "/.well-known/acme-challenge/",
    standard: "RFC 8555 §8.3",
    url: RFC(8555),
    status: "permanent",
    org: "IETF",
    registered: "2016-08-18",
    summary: "ACME http-01 domain-control challenge tokens.",
    deepDive: "acme-challenge",
  },
  {
    suffix: "agent-card.json",
    uri: "/.well-known/agent-card.json",
    standard: "A2A Protocol",
    url: "https://a2a-protocol.org/latest/specification/",
    status: "permanent",
    org: "Linux Foundation",
    registered: "2025-08-01",
    summary: "Agent-to-Agent agent card for agent discovery.",
    deepDive: "agent-card-json",
  },
  {
    suffix: "amphtml",
    uri: "/.well-known/amphtml",
    standard: "AMP cache update",
    url: "https://developers.google.com/amp/cache/update-cache",
    status: "provisional",
    org: "AMP Project (OpenJS)",
    registered: "2020-07-06",
    summary: "AMP cache update requests (update-cache protocol).",
  },
  {
    suffix: "api-catalog",
    uri: "/.well-known/api-catalog",
    standard: "RFC 9727",
    url: RFC(9727),
    status: "permanent",
    org: "IETF",
    registered: "2024-12-23",
    summary: "Machine-readable catalog of an origin's APIs.",
    deepDive: "api-catalog",
  },
  {
    suffix: "appspecific",
    uri: "/.well-known/appspecific/",
    standard: "appspecific spec",
    url: "https://github.com/Vroo/well-known-uri-appspecific",
    status: "provisional",
    org: "Bruce Leban",
    registered: "2021-06-01",
    summary: "Reverse-DNS namespace for application-specific files.",
  },
  {
    suffix: "ashrae",
    uri: "/.well-known/ashrae",
    standard: "BACnet",
    url: "http://www.bacnet.org/",
    status: "permanent",
    org: "ASHRAE",
    registered: "2016-01-22",
    summary: "BACnet building-automation well-known resource.",
  },
  {
    suffix: "assetlinks.json",
    uri: "/.well-known/assetlinks.json",
    standard: "Digital Asset Links",
    url: "https://developers.google.com/digital-asset-links",
    status: "permanent",
    org: "Google",
    registered: "2015-09-28",
    summary: "Android app-website association statements.",
    deepDive: "assetlinks-json",
  },
  {
    suffix: "broadband-labels",
    uri: "/.well-known/broadband-labels",
    standard: "Broadband label",
    url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5681704",
    status: "provisional",
    org: "BITAG",
    registered: "2024-08-30",
    summary: "Broadband consumer-disclosure labels.",
  },
  {
    suffix: "brski",
    uri: "/.well-known/brski",
    standard: "RFC 8995",
    url: RFC(8995),
    status: "permanent",
    org: "IETF",
    registered: "2020-10-09",
    summary: "Bootstrapping Remote Secure Key Infrastructure (BRSKI).",
  },
  {
    suffix: "caldav",
    uri: "/.well-known/caldav",
    standard: "RFC 6764",
    url: RFC(6764),
    status: "permanent",
    org: "IETF",
    registered: "-",
    summary: "CalDAV service autodiscovery.",
    deepDive: "caldav-carddav",
  },
  {
    suffix: "carddav",
    uri: "/.well-known/carddav",
    standard: "RFC 6764",
    url: RFC(6764),
    status: "permanent",
    org: "IETF",
    registered: "-",
    summary: "CardDAV service autodiscovery.",
    deepDive: "caldav-carddav",
  },
  {
    suffix: "change-password",
    uri: "/.well-known/change-password",
    standard: "W3C change-password-url",
    url: "https://w3c.github.io/webappsec-change-password-url/",
    status: "provisional",
    org: "W3C",
    registered: "2023-03-13",
    summary: "The URL browsers navigate to for password changes.",
    deepDive: "change-password",
  },
  {
    suffix: "cmp",
    uri: "/.well-known/cmp",
    standard: "RFC 9811 / 9482",
    url: RFC(9811),
    status: "permanent",
    org: "IETF",
    registered: "2021-05-20",
    summary: "Certificate Management Protocol (CMP) endpoints.",
  },
  {
    suffix: "coap",
    uri: "/.well-known/coap",
    standard: "RFC 8323",
    url: RFC(8323),
    status: "permanent",
    org: "IETF",
    registered: "2017-12-22",
    summary: "CoAP over TCP/TLS well-known resource.",
  },
  {
    suffix: "coap-eap",
    uri: "/.well-known/coap-eap",
    standard: "RFC 9820",
    url: RFC(9820),
    status: "permanent",
    org: "IETF",
    registered: "2025-02-14",
    summary: "CoAP EAP-based authentication endpoints.",
  },
  {
    suffix: "core",
    uri: "/.well-known/core",
    standard: "RFC 6690",
    url: RFC(6690),
    status: "permanent",
    org: "IETF",
    registered: "-",
    summary: "CoRE Link Format resource discovery (CoAP).",
  },
  {
    suffix: "csaf",
    uri: "/.well-known/csaf/",
    standard: "OASIS CSAF 2.0",
    url: "https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html",
    status: "provisional",
    org: "OASIS",
    registered: "2023-02-10",
    summary: "Security advisory feed metadata.",
    deepDive: "csaf",
  },
  {
    suffix: "csaf-aggregator",
    uri: "/.well-known/csaf-aggregator/",
    standard: "OASIS CSAF 2.0",
    url: "https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html",
    status: "provisional",
    org: "OASIS",
    registered: "2023-02-10",
    summary: "CSAF aggregator metadata for mirrored advisories.",
  },
  {
    suffix: "csipaus",
    uri: "/.well-known/csipaus",
    standard: "SA TS 5573:2025",
    url: "https://store.standards.org.au/product/sa-ts-5573-2025",
    status: "provisional",
    org: "CSIP-AUS",
    registered: "2026-07-31",
    summary: "Common Smart Inverter Profile (Australia).",
  },
  {
    suffix: "csvm",
    uri: "/.well-known/csvm",
    standard: "W3C CSV on the Web",
    url: "https://www.w3.org/TR/tabular-data-model/",
    status: "permanent",
    org: "W3C",
    registered: "2015-09-28",
    summary: "Site-wide CSV metadata.",
    deepDive: "csvm",
  },
  {
    suffix: "did.json",
    uri: "/.well-known/did.json",
    standard: "did:web",
    url: "https://w3c-ccg.github.io/did-method-web",
    status: "provisional",
    org: "W3C CCG",
    registered: "2023-01-31",
    summary: "did:web well-known DID document location.",
    deepDive: "did-json",
  },
  {
    suffix: "did-configuration.json",
    uri: "/.well-known/did-configuration.json",
    standard: "DIF DID Configuration",
    url: "https://identity.foundation/.well-known/resources/did-configuration",
    status: "provisional",
    org: "DIF",
    registered: "2023-01-31",
    summary: "Signed domain-DID linkage credential.",
    deepDive: "did-configuration",
  },
  {
    suffix: "dnt",
    uri: "/.well-known/dnt/",
    standard: "W3C Tracking DNT",
    url: "https://www.w3.org/TR/tracking-dnt/",
    status: "permanent",
    org: "W3C TPWG",
    registered: "2015-08-19",
    summary: "Do Not Track status resource.",
    deepDive: "dnt",
  },
  {
    suffix: "dnt-policy.txt",
    uri: "/.well-known/dnt-policy.txt",
    standard: "EFF DNT policy",
    url: "https://www.eff.org/dnt-policy",
    status: "permanent",
    org: "EFF",
    registered: "2015-08-19",
    summary: "DNT policy commitment file.",
    deepDive: "dnt-policy-txt",
  },
  {
    suffix: "dots",
    uri: "/.well-known/dots",
    standard: "RFC 9132",
    url: RFC(9132),
    status: "permanent",
    org: "IETF",
    registered: "2020-01-16",
    summary: "DDoS Open Threat Signaling (DOTS) gateway.",
  },
  {
    suffix: "easy-proxy",
    uri: "/.well-known/easy-proxy",
    standard: "G3 easy-proxy",
    url: "https://github.com/bytedance/g3/blob/master/doc/easy-proxy.md",
    status: "provisional",
    org: "The G3 Project",
    registered: "2025-05-01",
    summary: "ByteDance G3 easy-proxy discovery.",
  },
  {
    suffix: "ecips",
    uri: "/.well-known/ecips",
    standard: "ECIP",
    url: "https://ecips.that.world/24-ECIPURI",
    status: "provisional",
    org: "Wei Tang",
    registered: "2019-04-10",
    summary: "ECIP (Ethereum-class improvement) URI resource.",
  },
  {
    suffix: "edhoc",
    uri: "/.well-known/edhoc",
    standard: "RFC 9528",
    url: RFC(9528),
    status: "permanent",
    org: "IETF",
    registered: "2023-08-29",
    summary: "EDHOC lightweight authenticated key exchange.",
  },
  {
    suffix: "enterprise-network-security",
    uri: "/.well-known/enterprise-network-security",
    standard: "ETSI TS 103 523-5",
    url: "https://www.etsi.org/deliver/etsi_ts/103500_103599/10352305/",
    status: "permanent",
    org: "ETSI",
    registered: "2022-02-07",
    summary: "Smart-appliance network security enrollment.",
  },
  {
    suffix: "enterprise-transport-security",
    uri: "/.well-known/enterprise-transport-security",
    standard: "ETSI TS 103 523-3",
    url: "https://www.etsi.org/deliver/etsi_ts/103500_103599/10352303/",
    status: "permanent",
    org: "ETSI",
    registered: "2019-05-14",
    summary: "Smart-appliance transport security enrollment.",
  },
  {
    suffix: "est",
    uri: "/.well-known/est",
    standard: "RFC 7030 / 9148",
    url: RFC(7030),
    status: "permanent",
    org: "IETF",
    registered: "2013-08-16",
    summary: "Enrollment over Secure Transport (EST).",
    deepDive: "est",
  },
  {
    suffix: "funding-manifest-urls",
    uri: "/.well-known/funding-manifest-urls",
    standard: "funding.json",
    url: "https://fundingjson.org/",
    status: "provisional",
    org: "floss.fund",
    registered: "2025-04-02",
    summary: "Points at a project's funding manifest.",
    deepDive: "funding-manifest-urls",
  },
  {
    suffix: "genid",
    uri: "/.well-known/genid",
    standard: "RDF 1.1",
    url: "https://www.w3.org/TR/rdf11-concepts/",
    status: "permanent",
    org: "W3C",
    registered: "2012-11-15",
    summary: "RDF blank-node identifier generation service.",
  },
  {
    suffix: "gnap-as-rs",
    uri: "/.well-known/gnap-as-rs",
    standard: "RFC 9767 §3.1",
    url: RFC(9767),
    status: "permanent",
    org: "IETF",
    registered: "2024-10-23",
    summary: "GNAP AS-RS trust-relationship endpoint.",
    deepDive: "gnap-as-rs",
  },
  {
    suffix: "gpc.json",
    uri: "/.well-known/gpc.json",
    standard: "W3C GPC",
    url: "https://www.w3.org/TR/gpc/",
    status: "provisional",
    org: "W3C",
    registered: "2022-01-28",
    summary: "Global Privacy Control support statement.",
    deepDive: "gpc-json",
  },
  {
    suffix: "gs1resolver",
    uri: "/.well-known/gs1resolver",
    standard: "GS1 Digital Link",
    url: "https://www.gs1.org/docs/Digital-Link/",
    status: "permanent",
    org: "GS1",
    registered: "2020-05-18",
    summary: "GS1 Digital Link resolver discovery.",
  },
  {
    suffix: "hoba",
    uri: "/.well-known/hoba",
    standard: "RFC 7486 §6",
    url: RFC(7486),
    status: "permanent",
    org: "IETF",
    registered: "2015-01-20",
    summary: "HTTP Origin-Bound Authentication.",
    deepDive: "hoba",
  },
  {
    suffix: "host-meta",
    uri: "/.well-known/host-meta",
    standard: "RFC 6415",
    url: RFC(6415),
    status: "permanent",
    org: "IETF",
    registered: "-",
    summary: "XRD host metadata document.",
    deepDive: "host-meta",
  },
  {
    suffix: "host-meta.json",
    uri: "/.well-known/host-meta.json",
    standard: "RFC 6415",
    url: RFC(6415),
    status: "permanent",
    org: "IETF",
    registered: "-",
    summary: "JRD host metadata document.",
    deepDive: "host-meta",
  },
  {
    suffix: "hosting-provider",
    uri: "/.well-known/hosting-provider",
    standard: "Automattic hosting-provider",
    url: "https://github.com/Automattic/hosting-provider",
    status: "provisional",
    org: "Automattic",
    registered: "2020-07-21",
    summary: "Plain-text hint of the hosting provider.",
    deepDive: "hosting-provider",
  },
  {
    suffix: "http-opportunistic",
    uri: "/.well-known/http-opportunistic",
    standard: "RFC 8164 (historic)",
    url: RFC(8164),
    status: "obsoleted",
    org: "IETF",
    registered: "2017-03-20",
    summary: "Opportunistic HTTP security (historic — retired 2021).",
  },
  {
    suffix: "ic-domains",
    uri: "/.well-known/ic-domains",
    standard: "Internet Computer",
    url: "https://docs.internetcomputer.org/",
    status: "provisional",
    org: "DFINITY",
    registered: "2026-01-12",
    summary: "Internet Computer canister custom-domain declaration.",
  },
  {
    suffix: "idp-proxy",
    uri: "/.well-known/idp-proxy",
    standard: "RFC 8827",
    url: RFC(8827),
    status: "permanent",
    org: "IETF",
    registered: "2019-07-25",
    summary: "WebRTC identity proxy discovery.",
    deepDive: "idp-proxy",
  },
  {
    suffix: "jmap",
    uri: "/.well-known/jmap",
    standard: "RFC 8620 §2.2",
    url: RFC(8620),
    status: "permanent",
    org: "IETF",
    registered: "2019-03-28",
    summary: "JMAP session resource.",
    deepDive: "jmap",
  },
  {
    suffix: "keybase.txt",
    uri: "/.well-known/keybase.txt",
    standard: "Keybase",
    url: "https://keybase.io/__/keybase_well_known",
    status: "permanent",
    org: "Keybase",
    registered: "2014-04-08",
    summary: "Domain-ownership proof for Keybase identities.",
    deepDive: "keybase-txt",
  },
  {
    suffix: "knx",
    uri: "/.well-known/knx",
    standard: "KNX cloud",
    url: "https://knxcloud.org/",
    status: "provisional",
    org: "KNX Association",
    registered: "2023-08-15",
    summary: "KNX building-automation cloud discovery.",
  },
  {
    suffix: "looking-glass",
    uri: "/.well-known/looking-glass",
    standard: "RFC 8522 §2",
    url: RFC(8522),
    status: "permanent",
    org: "M. Stubbig",
    registered: "2018-12-07",
    summary: "Looking Glass protocol metadata (network diagnostics).",
  },
  {
    suffix: "masque",
    uri: "/.well-known/masque",
    standard: "RFC 9298 / 9484",
    url: RFC(9298),
    status: "permanent",
    org: "IETF",
    registered: "2022-06-23",
    summary: "MASQUE proxy protocol configuration.",
  },
  {
    suffix: "matrix",
    uri: "/.well-known/matrix/",
    standard: "Matrix",
    url: "https://spec.matrix.org/latest/client-server-api/#well-known-uri",
    status: "permanent",
    org: "Matrix.org Foundation",
    registered: "2019-04-16",
    summary: "Matrix homeserver delegation.",
    deepDive: "matrix",
  },
  {
    suffix: "mercure",
    uri: "/.well-known/mercure",
    standard: "Mercure",
    url: "https://mercure.rocks/spec",
    status: "provisional",
    org: "Les-Tilleuls.coop",
    registered: "2023-03-20",
    summary: "Mercure real-time hub discovery.",
    deepDive: "mercure",
  },
  {
    suffix: "mta-sts.txt",
    uri: "/.well-known/mta-sts.txt",
    standard: "RFC 8461",
    url: RFC(8461),
    status: "permanent",
    org: "IETF",
    registered: "2018-06-21",
    summary: "SMTP MTA Strict Transport Security policy.",
    deepDive: "mta-sts",
  },
  {
    suffix: "mud",
    uri: "/.well-known/mud",
    standard: "RFC 8520 (historic)",
    url: RFC(8520),
    status: "obsoleted",
    org: "IETF",
    registered: "2016-11-23",
    summary: "Manufacturer Usage Description (obsoleted 2021).",
  },
  {
    suffix: "nfv-oauth-server-configuration",
    uri: "/.well-known/nfv-oauth-server-configuration",
    standard: "ETSI GS NFV-SEC 022",
    url: "https://www.etsi.org/deliver/etsi_gs/NFV-SEC/001_099/022/",
    status: "permanent",
    org: "ETSI",
    registered: "2019-06-26",
    summary: "NFV OAuth server configuration discovery.",
  },
  {
    suffix: "ni",
    uri: "/.well-known/ni",
    standard: "RFC 6920",
    url: RFC(6920),
    status: "permanent",
    org: "IETF",
    registered: "-",
    summary: "Named Information (ni) URI dereferencing.",
  },
  {
    suffix: "nodeinfo",
    uri: "/.well-known/nodeinfo",
    standard: "NodeInfo 2.1",
    url: "https://nodeinfo.diaspora.software/",
    status: "provisional",
    org: "NodeInfo community",
    registered: "2024-07-29",
    summary: "Federated server software/usage metadata.",
    deepDive: "nodeinfo",
  },
  {
    suffix: "nostr.json",
    uri: "/.well-known/nostr.json",
    standard: "NIP-05",
    url: "https://github.com/nostr-protocol/nips/blob/master/05.md",
    status: "provisional",
    org: "Nostr community",
    registered: "2024-03-18",
    summary: "Nostr name-to-pubkey mapping.",
    deepDive: "nostr-json",
  },
  {
    suffix: "oauth-authorization-server",
    uri: "/.well-known/oauth-authorization-server",
    standard: "RFC 8414 §3",
    url: RFC(8414),
    status: "permanent",
    org: "IESG",
    registered: "2018-03-27",
    summary: "OAuth AS metadata.",
    deepDive: "oauth-authorization-server",
  },
  {
    suffix: "oauth-protected-resource",
    uri: "/.well-known/oauth-protected-resource",
    standard: "RFC 9728 §3",
    url: RFC(9728),
    status: "permanent",
    org: "IETF",
    registered: "2024-10-22",
    summary: "OAuth protected-resource metadata.",
    deepDive: "oauth-protected-resource",
  },
  {
    suffix: "ohttp-gateway",
    uri: "/.well-known/ohttp-gateway",
    standard: "RFC 9540",
    url: RFC(9540),
    status: "permanent",
    org: "IETF",
    registered: "2023-10-25",
    summary: "Oblivious HTTP gateway configuration.",
  },
  {
    suffix: "ojobpub.json",
    uri: "/.well-known/ojobpub.json",
    standard: "letsemploy.org",
    url: "https://docs.letsemploy.org",
    status: "provisional",
    org: "letsemploy.org",
    registered: "2026-05-12",
    summary: "Open Job Publication (ojobpub) manifest.",
  },
  {
    suffix: "openbindings",
    uri: "/.well-known/openbindings",
    standard: "OpenBindings",
    url: "https://openbindings.com/spec",
    status: "provisional",
    org: "OpenBindings Project",
    registered: "2026-05-13",
    summary: "OpenBindings specification discovery.",
  },
  {
    suffix: "openid-federation",
    uri: "/.well-known/openid-federation",
    standard: "OpenID Federation 1.0",
    url: "https://openid.net/specs/openid-federation-1_0.html",
    status: "provisional",
    org: "OpenID ABWG",
    registered: "2024-07-26",
    summary: "Federated trust statements.",
    deepDive: "openid-federation",
  },
  {
    suffix: "open-resource-discovery",
    uri: "/.well-known/open-resource-discovery",
    standard: "SAP Open Resource Discovery",
    url: "https://sap.github.io/open-resource-discovery/",
    status: "provisional",
    org: "SAP",
    registered: "2023-11-27",
    summary: "Link-format resource discovery.",
    deepDive: "open-resource-discovery",
  },
  {
    suffix: "openid-configuration",
    uri: "/.well-known/openid-configuration",
    standard: "OIDC Discovery 1.0",
    url: "https://openid.net/specs/openid-connect-discovery-1_0.html",
    status: "permanent",
    org: "OpenID Foundation",
    registered: "2013-08-27",
    summary: "OpenID Provider discovery document.",
    deepDive: "openid-configuration",
  },
  {
    suffix: "openorg",
    uri: "/.well-known/openorg",
    standard: "Open Data",
    url: "http://opd.data.ac.uk/",
    status: "permanent",
    org: "University of Southampton",
    registered: "2015-05-29",
    summary: "Open data publishing metadata.",
  },
  {
    suffix: "oslc",
    uri: "/.well-known/oslc",
    standard: "OASIS OSLC Core 3.0",
    url: "https://docs.oasis-open-projects.org/oslc-op/core/v3.0/oslc-core.html",
    status: "permanent",
    org: "OASIS",
    registered: "2020-12-29",
    summary: "OSLC tool discovery.",
    deepDive: "oslc",
  },
  {
    suffix: "pki-validation",
    uri: "/.well-known/pki-validation/",
    standard: "CA/B Forum BR §3.2.2.4.6",
    url: "https://cabforum.org/baseline-requirements-documents/",
    status: "permanent",
    org: "CA/Browser Forum",
    registered: "2017-02-06",
    summary: "File-based domain control validation.",
    deepDive: "pki-validation",
  },
  {
    suffix: "posh",
    uri: "/.well-known/posh/",
    standard: "RFC 7711",
    url: RFC(7711),
    status: "permanent",
    org: "IETF",
    registered: "2015-09-20",
    summary: "PKIX Over HTTP certificate publication.",
    deepDive: "posh",
  },
  {
    suffix: "privacy-sandbox-attestations.json",
    uri: "/.well-known/privacy-sandbox-attestations.json",
    standard: "Privacy Sandbox",
    url: "https://github.com/privacysandbox/attestation",
    status: "deprecated",
    org: "Google",
    registered: "2024-12-04",
    summary: "Privacy Sandbox API attestations (deprecated 2026).",
    deepDive: "privacy-sandbox-attestations",
  },
  {
    suffix: "private-token-issuer-directory",
    uri: "/.well-known/private-token-issuer-directory",
    standard: "RFC 9578",
    url: RFC(9578),
    status: "permanent",
    org: "IETF",
    registered: "2023-10-09",
    summary: "Private Access Token issuer directory.",
  },
  {
    suffix: "probing.txt",
    uri: "/.well-known/probing.txt",
    standard: "RFC 9511",
    url: RFC(9511),
    status: "permanent",
    org: "IETF",
    registered: "2023-09-01",
    summary: "Active-probing message format.",
  },
  {
    suffix: "pvd",
    uri: "/.well-known/pvd",
    standard: "RFC 8801",
    url: RFC(8801),
    status: "permanent",
    org: "IETF",
    registered: "2020-02-18",
    summary: "Provisioning Domains (IPv6 network info).",
  },
  {
    suffix: "rd",
    uri: "/.well-known/rd",
    standard: "RFC 9176",
    url: RFC(9176),
    status: "permanent",
    org: "IETF",
    registered: "2021-05-04",
    summary: "Reliable and Available Wireless (RAW) endpoint.",
  },
  {
    suffix: "related-website-set.json",
    uri: "/.well-known/related-website-set.json",
    standard: "Chrome RWS",
    url: "https://github.com/GoogleChrome/related-website-sets",
    status: "deprecated",
    org: "Google",
    registered: "2023-12-01",
    summary: "Related Website Sets declaration (deprecated 2026).",
    deepDive: "related-website-set-json",
  },
  {
    suffix: "reload-config",
    uri: "/.well-known/reload-config",
    standard: "RFC 6940",
    url: RFC(6940),
    status: "permanent",
    org: "IETF",
    registered: "-",
    summary: "RELOAD P2P overlay configuration.",
  },
  {
    suffix: "repute-template",
    uri: "/.well-known/repute-template",
    standard: "RFC 7072",
    url: RFC(7072),
    status: "permanent",
    org: "IETF",
    registered: "2013-09-30",
    summary: "Reputation query template.",
  },
  {
    suffix: "resourcesync",
    uri: "/.well-known/resourcesync",
    standard: "NISO Z39.99",
    url: "http://www.openarchives.org/rs/resourcesync",
    status: "permanent",
    org: "NISO",
    registered: "2017-05-26",
    summary: "ResourceSync capability discovery.",
    deepDive: "resourcesync",
  },
  {
    suffix: "sbom",
    uri: "/.well-known/sbom",
    standard: "RFC 9472",
    url: RFC(9472),
    status: "permanent",
    org: "IETF",
    registered: "2023-05-12",
    summary: "Software Bill of Materials discovery.",
    deepDive: "sbom",
  },
  {
    suffix: "scitt-keys",
    uri: "/.well-known/scitt-keys",
    standard: "RFC 9943",
    url: RFC(9943),
    status: "permanent",
    org: "IETF",
    registered: "2026-07-01",
    summary: "SCITT transparency service keys.",
    deepDive: "scitt-keys",
  },
  {
    suffix: "security.txt",
    uri: "/.well-known/security.txt",
    standard: "RFC 9116",
    url: RFC(9116),
    status: "permanent",
    org: "IETF",
    registered: "2021-07-13",
    summary: "Vulnerability disclosure contact.",
    deepDive: "security-txt",
  },
  {
    suffix: "ssf-configuration",
    uri: "/.well-known/ssf-configuration",
    standard: "OpenID Shared Signals",
    url: "https://openid.net/specs/openid-sharedsignals-framework-1_0.html",
    status: "provisional",
    org: "OpenID SSF WG",
    registered: "2024-04-18",
    summary: "Shared Signals Framework configuration.",
  },
  {
    suffix: "ssh-known-hosts",
    uri: "/.well-known/ssh-known-hosts",
    standard: "C2SP well-known-ssh-hosts",
    url: "https://c2sp.org/well-known-ssh-hosts",
    status: "provisional",
    org: "David Crawshaw",
    registered: "2025-12-16",
    summary: "SSH host keys published over HTTPS.",
    deepDive: "ssh-known-hosts",
  },
  {
    suffix: "sshfp",
    uri: "/.well-known/sshfp",
    standard: "SSHFP",
    url: "https://sshfp.github.io/sshfp.html",
    status: "provisional",
    org: "Cynthia Revström",
    registered: "2020-07-21",
    summary: "SSH fingerprint publication over HTTPS.",
  },
  {
    suffix: "stun-key",
    uri: "/.well-known/stun-key",
    standard: "RFC 7635",
    url: RFC(7635),
    status: "permanent",
    org: "IETF",
    registered: "2015-06-12",
    summary: "STUN key distribution (TURN auth).",
  },
  {
    suffix: "tea",
    uri: "/.well-known/tea",
    standard: "Transparency Exchange API",
    url: "https://tc54.org/tea/",
    status: "provisional",
    org: "ECMA TC54",
    registered: "2026-02-28",
    summary: "Transparency Exchange API discovery.",
  },
  {
    suffix: "terraform.json",
    uri: "/.well-known/terraform.json",
    standard: "Terraform",
    url: "https://developer.hashicorp.com/terraform/internals/remote-service-discovery",
    status: "provisional",
    org: "HashiCorp",
    registered: "2024-07-01",
    summary: "Terraform registry service discovery.",
    deepDive: "terraform-json",
  },
  {
    suffix: "thread",
    uri: "/.well-known/thread",
    standard: "Thread Group",
    url: "https://www.threadgroup.org/support#specifications",
    status: "permanent",
    org: "Thread Group",
    registered: "2018-11-29",
    summary: "Thread (IoT mesh) network configuration.",
  },
  {
    suffix: "time",
    uri: "/.well-known/time",
    standard: "Time",
    url: "http://phk.freebsd.dk/time/",
    status: "permanent",
    org: "Poul-Henning Kamp",
    registered: "2015-12-09",
    summary: "HTTP time protocol (subsecond timestamps).",
  },
  {
    suffix: "timezone",
    uri: "/.well-known/timezone",
    standard: "RFC 7808",
    url: RFC(7808),
    status: "permanent",
    org: "IESG",
    registered: "2015-08-03",
    summary: "Timezone service discovery.",
  },
  {
    suffix: "tdmrep.json",
    uri: "/.well-known/tdmrep.json",
    standard: "W3C TDMRep",
    url: "https://www.w3.org/2022/tdmrep/",
    status: "provisional",
    org: "W3C",
    registered: "2024-02-15",
    summary: "Text-and-data-mining policy.",
    deepDive: "tdmrep-json",
  },
  {
    suffix: "tor-relay",
    uri: "/.well-known/tor-relay/",
    standard: "Tor proposal 326",
    url:
      "https://gitlab.torproject.org/tpo/core/torspec/-/blob/main/proposals/326-tor-relay-well-known-uri-rfc8615.md",
    status: "provisional",
    org: "Tor Project",
    registered: "2020-10-06",
    summary: "Tor relay identity fingerprint.",
    deepDive: "tor-relay",
  },
  {
    suffix: "tpcd",
    uri: "/.well-known/tpcd/",
    standard: "3PCD grace period",
    url: "https://github.com/explainers-by-googlers/3pcd-grace-period-opt-out",
    status: "deprecated",
    org: "Google",
    registered: "2024-05-08",
    summary: "Third-party-cookie deprecation opt-out (deprecated 2026).",
  },
  {
    suffix: "traffic-advice",
    uri: "/.well-known/traffic-advice",
    standard: "Private prefetch proxy",
    url: "https://buettner.github.io/private-prefetch-proxy/traffic-advice.html",
    status: "provisional",
    org: "Jeremy Roman",
    registered: "2022-03-29",
    summary: "Traffic advice for the Private Prefetch Proxy.",
  },
  {
    suffix: "trust.txt",
    uri: "/.well-known/trust.txt",
    standard: "JournalList",
    url: "https://journallist.net/reference-document-for-trust-txt-specifications",
    status: "provisional",
    org: "JournalList.net",
    registered: "2022-02-04",
    summary: "Newsroom ownership/funding/corrections file.",
    deepDive: "trust-txt",
  },
  {
    suffix: "uma2-configuration",
    uri: "/.well-known/uma2-configuration",
    standard: "UMA 2.0",
    url: "https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html",
    status: "permanent",
    org: "Kantara UMA WG",
    registered: "2017-06-20",
    summary: "User-Managed Access AS configuration.",
    deepDive: "uma2-configuration",
  },
  {
    suffix: "void",
    uri: "/.well-known/void",
    standard: "W3C VoID",
    url: "https://www.w3.org/TR/void/",
    status: "permanent",
    org: "W3C",
    registered: "2011-05-11",
    summary: "VoID dataset description.",
    deepDive: "void",
  },
  {
    suffix: "webauthn",
    uri: "/.well-known/webauthn",
    standard: "W3C WebAuthn 3",
    url: "https://www.w3.org/TR/webauthn-3/",
    status: "permanent",
    org: "W3C",
    registered: "2026-01-23",
    summary: "WebAuthn related-origin authorization.",
    deepDive: "webauthn",
  },
  {
    suffix: "webfinger",
    uri: "/.well-known/webfinger",
    standard: "RFC 7033",
    url: RFC(7033),
    status: "permanent",
    org: "IETF",
    registered: "2013-03-15",
    summary: "Account/entity discovery (JRD).",
    deepDive: "webfinger",
  },
  {
    suffix: "webhook-authorized-senders.json",
    uri: "/.well-known/webhook-authorized-senders.json",
    standard: "Intempus webhook auth",
    url: "https://intempus.dk/webhook-authorization",
    status: "permanent",
    org: "Intempus",
    registered: "2025-09-29",
    summary: "Authorized webhook senders manifest.",
  },
  {
    suffix: "webweaver.json",
    uri: "/.well-known/webweaver.json",
    standard: "webweaver",
    url: "https://www.webweaver.de/well-known",
    status: "provisional",
    org: "DigiOnline",
    registered: "2022-08-11",
    summary: "School platform federation registry.",
    deepDive: "webweaver-json",
  },
  {
    suffix: "wot",
    uri: "/.well-known/wot",
    standard: "W3C WoT Discovery",
    url: "https://www.w3.org/TR/wot-discovery/",
    status: "permanent",
    org: "W3C WoT WG",
    registered: "2023-01-24",
    summary: "Web of Things discovery metadata.",
  },
];

/** De-facto well-known URIs that are widely deployed but not IANA-registered. */
export const DEFACTO: RegistryEntry[] = [
  {
    suffix: "jwks.json",
    uri: "/.well-known/jwks.json",
    standard: "RFC 7517 (JWK Set)",
    url: RFC(7517),
    status: "de-facto",
    org: "OAuth/OIDC ecosystem",
    registered: "-",
    summary: "Public keys for verifying signed tokens.",
    deepDive: "jwks-json",
  },
  {
    suffix: "oidc-registration",
    uri: "/.well-known/oidc-registration",
    standard: "OIDC Dynamic Client Registration 1.0",
    url: "https://openid.net/specs/openid-connect-registration-1_0.html",
    status: "de-facto",
    org: "OpenID ecosystem",
    registered: "-",
    summary: "Conventional path for dynamic client registration.",
    deepDive: "oidc-registration",
  },
  {
    suffix: "apple-app-site-association",
    uri: "/.well-known/apple-app-site-association",
    standard: "Apple Associated Domains",
    url: "https://developer.apple.com/documentation/xcode/supporting-associated-domains",
    status: "de-facto",
    org: "Apple",
    registered: "-",
    summary: "Universal links / webcredentials app association.",
    deepDive: "apple-app-site-association",
  },
  {
    suffix: "autoconfig",
    uri: "/.well-known/autoconfig/mail/config-v1.1.xml",
    standard: "Mozilla autoconfig",
    url: "https://wiki.mozilla.org/Thunderbird:Autoconfiguration",
    status: "de-facto",
    org: "Mozilla",
    registered: "-",
    summary: "Mail client auto-configuration XML.",
    deepDive: "autoconfig",
  },
  {
    suffix: "autodiscover",
    uri: "/.well-known/autodiscover/autodiscover.xml",
    standard: "Microsoft Autodiscover",
    url:
      "https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/autodiscover-for-exchange",
    status: "de-facto",
    org: "Microsoft",
    registered: "-",
    summary: "Exchange/mail client settings discovery.",
    deepDive: "autodiscover",
  },
  {
    suffix: "dns-query",
    uri: "/.well-known/dns-query",
    standard: "RFC 8484 (DoH)",
    url: RFC(8484),
    status: "de-facto",
    org: "IETF (default path)",
    registered: "-",
    summary: "Default DNS-over-HTTPS endpoint.",
    deepDive: "dns-query",
  },
  {
    suffix: "openpgpkey",
    uri: "/.well-known/openpgpkey/",
    standard: "RFC 7929 (WKD)",
    url: RFC(7929),
    status: "de-facto",
    org: "IETF (OpenPGP)",
    registered: "-",
    summary: "OpenPGP Web Key Directory.",
    deepDive: "openpgpkey",
  },
  {
    suffix: "lnurlp",
    uri: "/.well-known/lnurlp/<user>",
    standard: "LNURL LUD-06",
    url: "https://lnurl.dev/luds/06",
    status: "de-facto",
    org: "LNURL community",
    registered: "-",
    summary: "Lightning Address payRequest discovery.",
    deepDive: "lnurlp",
  },
  {
    suffix: "wac",
    uri: "/.well-known/wac",
    standard: "Solid WAC",
    url: "https://solidproject.org/TR/wac",
    status: "de-facto",
    org: "Solid project",
    registered: "-",
    summary: "Root ACL resource for Solid pods.",
    deepDive: "wac",
  },
  {
    suffix: "aarc",
    uri: "/.well-known/aarc",
    standard: "AARC community",
    url: "https://aarc-community.org/",
    status: "de-facto",
    org: "AARC (GÉANT)",
    registered: "-",
    summary: "Research AAI metadata (community-referenced).",
    deepDive: "aarc",
  },
  {
    suffix: "hosting-provider",
    uri: "/.well-known/hosting-provider",
    standard: "Automattic hosting-provider",
    url: "https://github.com/Automattic/hosting-provider",
    status: "iana",
    org: "Automattic",
    registered: "2020-07-21",
    summary: "Plain-text hint of the hosting provider.",
    deepDive: "hosting-provider",
  },
  {
    suffix: "llms.txt",
    uri: "/.well-known/llms.txt",
    standard: "llms.txt convention",
    url: "https://llmstxt.org/",
    status: "de-facto",
    org: "community",
    registered: "2025",
    summary: "Markdown summary of a site curated for LLM context ingestion.",
  },
  {
    suffix: "ai-plugin.json",
    uri: "/.well-known/ai-plugin.json",
    standard: "ChatGPT plugins (legacy)",
    url: "https://platform.openai.com/docs/plugins/introduction",
    status: "de-facto",
    org: "OpenAI",
    registered: "2023",
    summary: "Legacy manifest describing an AI tool plugin (superseded by MCP).",
  },
  {
    suffix: "authzen-configuration",
    uri: "/.well-known/authzen-configuration",
    standard: "OpenID AuthZEN",
    url: "https://openid.net/specs/openid-authzen-1_0.html",
    status: "de-facto",
    org: "OpenID AuthZEN Working Group",
    registered: "2025",
    summary: "Policy Decision Point discovery for fine-grained authorization.",
  },
  {
    suffix: "manifest.webmanifest",
    uri: "/.well-known/manifest.webmanifest",
    standard: "Isolated Web Apps (Chrome / WICG)",
    url: "https://github.com/WICG/isolated-web-apps",
    status: "de-facto",
    org: "WICG / Chrome",
    registered: "2024",
    summary: "Fixed manifest location Isolated Web Apps must use for install discovery.",
    deepDive: "manifest-webmanifest",
  },
  {
    suffix: "web-app-origin-association",
    uri: "/.well-known/web-app-origin-association",
    standard: "Web App Scope Extensions (WICG / Chrome)",
    url: "https://github.com/WICG/manifest-incubations/blob/gh-pages/scope_extensions-explainer.md",
    status: "de-facto",
    org: "WICG / Chrome",
    registered: "2023",
    summary: "Validation file a target origin hosts to grant a PWA extended scope.",
    deepDive: "web-app-origin-association",
  },
];
